apiVersion: 1
datasources:
  - name: Prometheus
    uid: reconx-prometheus
    type: prometheus
    access: proxy
    url: http://load-prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 5s
